# Author:Shazia Imran Shaikh


# Topic:Loan Predictions Using ML

In [1]:
%matplotlib inline
import numpy as np 
import pandas as pd
import seaborn as sns
sns.set(style='darkgrid')
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Loan_data.csv")

In [3]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
df=df.dropna()

In [5]:
df.reset_index(drop=True)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001003    Male     Yes          1      Graduate            No   
1    LP001005    Male     Yes          0      Graduate           Yes   
2    LP001006    Male     Yes          0  Not Graduate            No   
3    LP001008    Male      No          0      Graduate            No   
4    LP001011    Male     Yes          2      Graduate           Yes   
..        ...     ...     ...        ...           ...           ...   
475  LP002978  Female      No          0      Graduate            No   
476  LP002979    Male     Yes         3+      Graduate            No   
477  LP002983    Male     Yes          1      Graduate            No   
478  LP002984    Male     Yes          2      Graduate            No   
479  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               4583             1508.0       128.0             360.0   
1               3000                0.0        66.0             360.0   
2               2583             2358.0       120.0             360.0   
3               6000                0.0       141.0             360.0   
4               5417             4196.0       267.0             360.0   
..               ...                ...         ...               ...   
475             2900                0.0        71.0             360.0   
476             4106                0.0        40.0             180.0   
477             8072              240.0       253.0             360.0   
478             7583                0.0       187.0             360.0   
479             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Rural           N  
1               1.0         Urban           Y  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
475             1.0         Rural           Y  
476             1.0         Rural           Y  
477             1.0         Urban           Y  
478             1.0         Urban           Y  
479             0.0     Semiurban           N  

[480 rows x 13 columns]

In [6]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [7]:
df['Dependents'] = df['Dependents'].str.rstrip('+')
df['Dependents'] = df['Dependents'].astype(np.int32)
df['Gender'] = df['Gender'].map({'Female':0,'Male':1}).astype(np.int32)
df['Married'] = df['Married'].map({'No':0, 'Yes':1}).astype(np.int32)
df['Education'] = df['Education'].map({'Not Graduate':0, 'Graduate':1}).astype(np.int32)
df['Self_Employed'] = df['Self_Employed'].map({'No':0, 'Yes':1}).astype(np.int32)
df['Loan_Status'] = df['Loan_Status'].map({'N':0, 'Y':1}).astype(np.int32)
df['Property_Area'] = df['Property_Area'].map({'Rural':0, 'Urban':1,'Semiurban':2}).astype(np.int32)

In [8]:
df.head(100)

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
1    LP001003       1        1           1          1              0   
2    LP001005       1        1           0          1              1   
3    LP001006       1        1           0          0              0   
4    LP001008       1        0           0          1              0   
5    LP001011       1        1           2          1              1   
..        ...     ...      ...         ...        ...            ...   
128  LP001451       1        1           1          1              1   
131  LP001473       1        0           0          1              0   
132  LP001478       1        0           0          1              0   
133  LP001482       1        1           0          1              1   
134  LP001487       1        0           0          1              0   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
5               5417             4196.0       267.0             360.0   
..               ...                ...         ...               ...   
128            10513             3850.0       160.0             180.0   
131             2014             1929.0        74.0             360.0   
132             2718                0.0        70.0             360.0   
133             3459                0.0        25.0             120.0   
134             4895                0.0       102.0             360.0   

     Credit_History  Property_Area  Loan_Status  
1               1.0              0            0  
2               1.0              1            1  
3               1.0              1            1  
4               1.0              1            1  
5               1.0              1            1  
..              ...            ...          ...  
128             0.0              1            0  
131             1.0              1            1  
132             1.0              2            1  
133             1.0              2            1  
134             1.0              2            1  

[100 rows x 13 columns]

In [9]:
df.dtypes

Loan_ID               object
Gender                 int32
Married                int32
Dependents             int32
Education              int32
Self_Employed          int32
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area          int32
Loan_Status            int32
dtype: object

Dividing the given train dataset in the form of features and target variables 

In [10]:
X,y  = df.iloc[:, 1:-1], df.iloc[:, -1]

In [11]:
df.corr()

Gender   Married  Dependents  Education  Self_Employed  \
Gender             1.000000  0.349424    0.217510  -0.059245      -0.002761   
Married            0.349424  1.000000    0.386367  -0.001652       0.015674   
Dependents         0.217510  0.386367    1.000000  -0.028608       0.045754   
Education         -0.059245 -0.001652   -0.028608   1.000000       0.005085   
Self_Employed     -0.002761  0.015674    0.045754   0.005085       1.000000   
ApplicantIncome    0.032644  0.036717    0.131139   0.131172       0.170785   
CoapplicantIncome  0.156171  0.102950   -0.000318   0.074499      -0.001509   
LoanAmount         0.098975  0.183442    0.172780   0.172780       0.120389   
Loan_Amount_Term  -0.088704 -0.107504   -0.096361   0.102168      -0.034852   
Credit_History     0.022447  0.029095   -0.026651   0.056656      -0.023568   
Property_Area     -0.097035  0.028167   -0.030838   0.060010      -0.037900   
Loan_Status        0.064504  0.112321    0.035428   0.068437      -0.034715   

                   ApplicantIncome  CoapplicantIncome  LoanAmount  \
Gender                    0.032644           0.156171    0.098975   
Married                   0.036717           0.102950    0.183442   
Dependents                0.131139          -0.000318    0.172780   
Education                 0.131172           0.074499    0.172780   
Self_Employed             0.170785          -0.001509    0.120389   
ApplicantIncome           1.000000          -0.112588    0.495310   
CoapplicantIncome        -0.112588           1.000000    0.190740   
LoanAmount                0.495310           0.190740    1.000000   
Loan_Amount_Term         -0.010838          -0.005775    0.050867   
Credit_History           -0.056152          -0.008692   -0.040773   
Property_Area            -0.024586          -0.004348   -0.039807   
Loan_Status              -0.043152          -0.049020   -0.071753   

                   Loan_Amount_Term  Credit_History  Property_Area  \
Gender                    -0.088704        0.022447      -0.097035   
Married                   -0.107504        0.029095       0.028167   
Dependents                -0.096361       -0.026651      -0.030838   
Education                  0.102168        0.056656       0.060010   
Self_Employed             -0.034852       -0.023568      -0.037900   
ApplicantIncome           -0.010838       -0.056152      -0.024586   
CoapplicantIncome         -0.005775       -0.008692      -0.004348   
LoanAmount                 0.050867       -0.040773      -0.039807   
Loan_Amount_Term           1.000000        0.032937      -0.000568   
Credit_History             0.032937        1.000000       0.040092   
Property_Area             -0.000568        0.040092       1.000000   
Loan_Status               -0.007798        0.529390       0.153843   

                   Loan_Status  
Gender                0.064504  
Married               0.112321  
Dependents            0.035428  
Education             0.068437  
Self_Employed        -0.034715  
ApplicantIncome      -0.043152  
CoapplicantIncome    -0.049020  
LoanAmount           -0.071753  
Loan_Amount_Term     -0.007798  
Credit_History        0.529390  
Property_Area         0.153843  
Loan_Status           1.000000

In [12]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)

In [13]:
# We split the X into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)


Train set: (384, 11) (384,)
Test set: (96, 11) (96,)


In [14]:
#C is inverse to lambda .
#It is the hyperparameter which controls the regularization basically to avoid overfitting the model.
from sklearn.linear_model import LogisticRegression
LR_model = LogisticRegression(C=0.01).fit(X_train,y_train)
LR_model

LogisticRegression(C=0.01)

In [15]:
y_test=y_test.ravel()
y_test

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1])

In [16]:
y_pred = LR_model.predict(X_test)
y_pred=y_pred.ravel()
y_pred


array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1])

In [17]:
#Predict will give either 0 or 1 as output
#Predict_proba will give the only probability of occurence of 0 and 1.
LR_yhat_prob = LR_model.predict_proba(X_test)
LR_yhat_prob

array([[0.34037954, 0.65962046],
       [0.22518036, 0.77481964],
       [0.23874808, 0.76125192],
       [0.20618965, 0.79381035],
       [0.18266427, 0.81733573],
       [0.30481944, 0.69518056],
       [0.24221699, 0.75778301],
       [0.52107945, 0.47892055],
       [0.25557668, 0.74442332],
       [0.19840901, 0.80159099],
       [0.5826325 , 0.4173675 ],
       [0.24625342, 0.75374658],
       [0.27808547, 0.72191453],
       [0.34497656, 0.65502344],
       [0.24693077, 0.75306923],
       [0.21830983, 0.78169017],
       [0.2387195 , 0.7612805 ],
       [0.25740893, 0.74259107],
       [0.27523173, 0.72476827],
       [0.22367022, 0.77632978],
       [0.56188821, 0.43811179],
       [0.22898087, 0.77101913],
       [0.33538293, 0.66461707],
       [0.33756816, 0.66243184],
       [0.50473228, 0.49526772],
       [0.52967624, 0.47032376],
       [0.51621847, 0.48378153],
       [0.24407841, 0.75592159],
       [0.24225074, 0.75774926],
       [0.21370762, 0.78629238],
       [0.

In [18]:
LR_yhat_prob.shape

(96, 2)

In [19]:
#The F-score, also called the F1-score, is a measure of a model’s accuracy on a dataset
#The F-score is a way of combining the precision and recall of the model, and it is defined as the harmonic mean of the model’s precision and recall.
from sklearn.metrics import f1_score
print("Logistic Regression F1-score: %.2f" % f1_score(y_test, y_pred) )


Logistic Regression F1-score: 0.83


In [20]:
from sklearn.metrics import mean_absolute_error
#evaluation predictions
mae=mean_absolute_error(y_test,y_pred)
print('MAE:%.3f'% mae)

MAE:0.260


In [21]:
#Log-loss is indicative of how close the prediction probability is to the corresponding actual/true value (0 or 1 in case of binary classification). 
#The more the predicted probability diverges from the actual value, the higher is the log-loss value.
from sklearn.metrics import log_loss
"LR LogLoss:%.2f"%(log_loss(y_pred, LR_yhat_prob))

'LR LogLoss:0.34'

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
confusion_matrix
#The result is telling us that we have 12+59=71 correct predictions and 2+23=25 wrong predictions.(71+25=96)

array([[12, 23],
       [ 2, 59]], dtype=int64)